name: contador
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  path: ^1.8.0
  provider: ^6.1.1
  sqflite: ^2.3.2
  path_provider: ^2.0.15
  mobx: ^2.0.0
  flutter_mobx: ^2.2.0+2
  mobx_codegen: ^2.6.0+1  # Change this line
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mobx_codegen: ^2.0.2
  build_runner: ^2.1.4
  json_annotation: ^4.0.1
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true
  assets:
    - lib/stores/
    - assets/logo_cedrinho.jpg